apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      version: "v1"
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        version: "v1"
    spec:
      imagePullSecrets:
      - name: gitlab-auth
      containers:
      - name: default
        image: {{ .Values.docker_image }}
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 20
          periodSeconds: 15
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 120

