apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - host: {{ .Release.Namespace }}.{{ .Values.domain_name }}
    http:
      paths:
      - path: /*
        backend:
          serviceName: {{ .Release.Name }}
          servicePort: 80
