
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-auth
  namespace: {{ .Release.Namespace }}
  creationTimestamp: null
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.docker_registry (printf "%s:%s" .Values.docker_username .Values.docker_password | b64enc) | b64enc }}